import { Sku } from "./types";

// This is an expanded, manually curated list of products based on your data.
// It provides a wide variety of product types and sizes for realistic testing.
export const demoSkus: Sku[] = [
  {
    skuId: 'sku-aquafina-1l',
    name: 'AQUAFINA 1.0 L PET 12 Rs20',
    productType: 'PET_LARGE',
    width: 85, height: 25,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079921448.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-7up-fizz-250',
    name: '7 UP FIZZ 250ML PET 30Rs20 PROMO',
    productType: 'PET_SMALL',
    width: 70, height: 15,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079920301.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-creambell-kesar-180',
    name: 'CB MILK KESAR BADAM 180ML PET30 RS20',
    productType: 'PET_SMALL',
    width: 70, height: 18,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079922137.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-mirinda-750',
    name: 'MIRINDA ORANGE MID CAL 750ML PET24 Rs40',
    productType: 'PET_LARGE',
    width: 90, height: 27,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079923626.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-dew-250',
    name: 'MOUNTAIN DEW 250ml PET 24 Rs20',
    productType: 'PET_SMALL',
    width: 70, height: 15,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079924184.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-pepsi-400',
    name: 'PEPSI COLA 400ml PET30 Rs20',
    productType: 'PET_SMALL',
    width: 70, height: 18,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079925322.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-sting-250',
    name: 'STING 250ML rPET 30 RS20',
    productType: 'PET_SMALL',
    width: 70, height: 15,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079926983.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-tropicana-pomeg-180',
    name: 'TROP PR POMEG DLGHT 180ML TETRA 30 Rs20',
    productType: 'TETRA',
    width: 65, height: 15,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079931007.jpg',
    constraints: { stackable: true, deletable: true },
  },
  {
    skuId: 'sku-slice-350',
    name: 'TROPICANA SLICE 350ml PET 30 Rs20 NF',
    productType: 'PET_SMALL',
    width: 70, height: 18,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079926305.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-tropicana-orange-180-pet',
    name: 'TROP PR ORANGE DELIGHT 180ML PET30 Rs20',
    productType: 'PET_SMALL',
    width: 70, height: 18,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079930899.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-tropicana-appletini-180',
    name: 'TROP FRUTZ APPLETINI 180ML TETRA30 RS20',
    productType: 'TETRA',
    width: 65, height: 15,
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079927292.jpg',
    constraints: { stackable: true, deletable: true },
  },
  // --- NEW ITEMS ADDED BELOW ---
  {
    skuId: 'sku-blank-space',
    name: 'Blank Space',
    productType: 'BLANK', // A generic type that can be allowed anywhere
    width: 50, height: 10,
    imageUrl: 'https://placehold.co/50x100/e2e8f0/94a3b8?text=Empty',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-placeholder-rgb',
    name: 'Glass Bottle (Generic)',
    productType: 'RGB',
    width: 55, height: 16,
    imageUrl: 'https://placehold.co/55x160/f1f5f9/64748b?text=Glass',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-placeholder-chips',
    name: 'Chips Bag (Generic)',
    productType: 'CHIPS',
    width: 120, height: 16,
    imageUrl: 'https://placehold.co/120x160/fef9c3/f59e0b?text=Chips',
    constraints: { stackable: true, deletable: true },
  },
];