import { Sku } from "./types";
import { PIXELS_PER_MM } from "./config"; // Import the scale factor

// This is an expanded, manually curated list of products.
// Dimensions are now defined in real-world millimeters (MM) and converted to pixels.
export const demoSkus: Sku[] = [
  {
    skuId: 'sku-aquafina-1l',
    name: 'AQUAFINA 1.0 L PET 12 Rs20',
    productType: 'PET_LARGE',
    widthMM: 85, heightMM: 300,
    width: Math.round(85 * PIXELS_PER_MM), 
    height: Math.round(300 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079921448.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-7up-fizz-250',
    name: '7 UP FIZZ 250ML PET 30Rs20 PROMO',
    productType: 'PET_SMALL',
    widthMM: 55, heightMM: 180,
    width: Math.round(55 * PIXELS_PER_MM),
    height: Math.round(180 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079920301.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-creambell-kesar-180',
    name: 'CB MILK KESAR BADAM 180ML PET30 RS20',
    productType: 'PET_SMALL',
    widthMM: 50, heightMM: 160,
    width: Math.round(50 * PIXELS_PER_MM),
    height: Math.round(160 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079922137.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-mirinda-750',
    name: 'MIRINDA ORANGE MID CAL 750ML PET24 Rs40',
    productType: 'PET_LARGE',
    widthMM: 75, heightMM: 280,
    width: Math.round(75 * PIXELS_PER_MM),
    height: Math.round(280 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079923626.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-dew-250',
    name: 'MOUNTAIN DEW 250ml PET 24 Rs20',
    productType: 'PET_SMALL',
    widthMM: 55, heightMM: 180,
    width: Math.round(55 * PIXELS_PER_MM),
    height: Math.round(180 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079924184.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-pepsi-400',
    name: 'PEPSI COLA 400ml PET30 Rs20',
    productType: 'PET_SMALL',
    widthMM: 65, heightMM: 220,
    width: Math.round(65 * PIXELS_PER_MM),
    height: Math.round(220 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079925322.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-sting-250',
    name: 'STING 250ML rPET 30 RS20',
    productType: 'PET_SMALL',
    widthMM: 55, heightMM: 180,
    width: Math.round(55 * PIXELS_PER_MM),
    height: Math.round(180 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079926983.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-tropicana-pomeg-180',
    name: 'TROP PR POMEG DLGHT 180ML TETRA 30 Rs20',
    productType: 'TETRA',
    widthMM: 60, heightMM: 120,
    width: Math.round(60 * PIXELS_PER_MM),
    height: Math.round(120 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/dev/03/Skus/1755079931007.jpg',
    constraints: { stackable: true, deletable: true },
  },
  {
    skuId: 'sku-pepsi-can-330',
    name: 'Pepsi Can 330ml',
    productType: 'CAN',
    widthMM: 66, heightMM: 115,
    width: Math.round(66 * PIXELS_PER_MM),
    height: Math.round(115 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/prod/04/Skus/1755079920301.jpg',
    constraints: { stackable: true, deletable: true },
  },
  {
    skuId: 'sku-mirinda-1.25l',
    name: 'MIRINDA ORANGE 1.25L PET',
    productType: 'PET_LARGE',
    widthMM: 95, heightMM: 310,
    width: Math.round(95 * PIXELS_PER_MM),
    height: Math.round(310 * PIXELS_PER_MM),
    imageUrl: 'https://storage.googleapis.com/shelfex-cdn/shelfscan/prod/04/Skus/1753153765623.jpg',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-blank-space',
    name: 'Blank Space',
    productType: 'BLANK',
    widthMM: 100, heightMM: 20, // 100mm wide space
    width: Math.round(100 * PIXELS_PER_MM),
    height: Math.round(20 * PIXELS_PER_MM),
    imageUrl: 'https://placehold.co/50x10/e2e8f0/94a3b8?text=Empty',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-placeholder-chips',
    name: 'Chips Bag (Generic)',
    productType: 'CHIPS',
    widthMM: 180, heightMM: 250,
    width: Math.round(180 * PIXELS_PER_MM),
    height: Math.round(250 * PIXELS_PER_MM),
    imageUrl: 'https://placehold.co/90x125/fef9c3/f59e0b?text=Chips',
    constraints: { stackable: true, deletable: true },
  },
];