import { Sku } from "./types";
import { PIXELS_PER_MM } from "./config"; // Import the scale factor

// This is an expanded, manually curated list of products.
// Dimensions are now defined in real-world millimeters (MM) and converted to pixels.
export const demoSkus: Sku[] = [
  {
    skuId: 'sku-aquafina-1l',
    name: 'AQUAFINA 1.0 L PET 12 Rs20',
    productType: 'PET_LARGE',
    widthMM: 80, heightMM: 265,
    width: Math.round(80 * PIXELS_PER_MM), 
    height: Math.round(265 * PIXELS_PER_MM),
    imageUrl: './sku/AQUAFINA-1-L-PET-12-Rs20.png',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-7up-fizz-250',
    name: '7 UP FIZZ 250ML PET 30Rs20 PROMO',
    productType: 'PET_SMALL',
    widthMM: 60, heightMM: 170,
    width: Math.round(60 * PIXELS_PER_MM),
    height: Math.round(170 * PIXELS_PER_MM),
    imageUrl: './sku/7-UP-FIZZ-250ML-PET.png',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-creambell-kesar-180',
    name: 'CB MILK KESAR BADAM 180ML PET30 RS20',
    productType: 'PET_SMALL',
    widthMM: 66, heightMM: 165,
    width: Math.round(66 * PIXELS_PER_MM),
    height: Math.round(165 * PIXELS_PER_MM),
    imageUrl: './sku/CB-MILK-KESAR-BADAM-180ML.png',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-mirinda-750',
    name: 'MIRINDA ORANGE MID CAL 750ML PET24 Rs40',
    productType: 'PET_LARGE',
    widthMM: 80, heightMM: 265,
    width: Math.round(80 * PIXELS_PER_MM),
    height: Math.round(265 * PIXELS_PER_MM),
    imageUrl: './sku/MIRINDA-ORANGE-MID-CAL-750ML.png',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-dew-250',
    name: 'MOUNTAIN DEW 250ml PET 24 Rs20',
    productType: 'PET_SMALL',
    widthMM: 55, heightMM: 190,
    width: Math.round(55 * PIXELS_PER_MM),
    height: Math.round(190 * PIXELS_PER_MM),
    imageUrl: './sku/MOUNTAIN-DEW-250ml.png',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-pepsi-400',
    name: 'PEPSI COLA 750ml PET 24 Rs40',
    productType: 'PET_SMALL',
    widthMM: 75, heightMM: 270,
    width: Math.round(75 * PIXELS_PER_MM),
    height: Math.round(270 * PIXELS_PER_MM),
    imageUrl: './sku/PEPSI-COLA-400ml.png',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-sting-250',
    name: 'STING 250ML rPET 30 RS20',
    productType: 'PET_SMALL',
    widthMM: 52, heightMM: 135,
    width: Math.round(52 * PIXELS_PER_MM),
    height: Math.round(135 * PIXELS_PER_MM),
    imageUrl: './sku/STING-250ML-rPET.png',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-tropicana-pomeg-180',
    name: 'TROP PR POMEG DLGHT 180ML TETRA 30 Rs20',
    productType: 'TETRA',
    widthMM: 39, heightMM: 120,
    width: Math.round(39 * PIXELS_PER_MM),
    height: Math.round(120 * PIXELS_PER_MM),
    imageUrl: './sku/TROP-PR-POMEG-DLGHT-180ML.png',
    constraints: { stackable: true, deletable: true },
  },
  {
    skuId: 'sku-pepsi-can-330',
    name: 'Pepsi Can 330ml',
    productType: 'CAN',
    widthMM: 65, heightMM: 115,
    width: Math.round(65 * PIXELS_PER_MM),
    height: Math.round(115 * PIXELS_PER_MM),
    imageUrl: './sku/Pepsi-Can-330ml.png',
    constraints: { stackable: true, deletable: true },
  },
  {
    skuId: 'sku-mirinda-2l',
    name: 'MIRINDA ORANGE 2L PET',
    productType: 'PET_LARGE',
    widthMM: 102, heightMM: 334,
    width: Math.round(102 * PIXELS_PER_MM),
    height: Math.round(334 * PIXELS_PER_MM),
    imageUrl: './sku/MIRINDA-ORANGE-1.25L.png',
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-mirinda-1l',
    name: 'MIRINDA ORANGE 1L PET',
    productType: 'PET_LARGE',
    widthMM: 83, heightMM: 278,
    width: Math.round(83 * PIXELS_PER_MM),
    height: Math.round(278 * PIXELS_PER_MM),
    imageUrl: './sku/MIRINDA-ORANGE-1.25L.png',
    constraints: { stackable: false, deletable: true },  },
  {
    skuId: 'sku-blank-space',
    name: 'Blank Space',
    productType: 'BLANK',
    widthMM: 10, // Default 10mm width
    heightMM: 100, // Will be overridden by row height
    width: Math.round(10 * PIXELS_PER_MM),
    height: Math.round(100 * PIXELS_PER_MM),
    imageUrl: 'https://placehold.co/10x100/e0e7ff/6366f1?text=', // Blue tint for visibility
    constraints: { stackable: false, deletable: true },
  },
  {
    skuId: 'sku-placeholder-chips',
    name: 'Chips Bag (Generic)',
    productType: 'CHIPS',
    widthMM: 180, heightMM: 250,
    width: Math.round(180 * PIXELS_PER_MM),
    height: Math.round(250 * PIXELS_PER_MM),
    imageUrl: 'https://placehold.co/90x125/fef9c3/f59e0b?text=Chips',
    constraints: { stackable: true, deletable: true },
  },
];